### ISSUE TITLE
Question about contributing

### ISSUE THREAD

**Issue by jasonprogrammer** [guzba/mummy#19]
This project looks great. Are there ways I could help contribute? Is there a roadmap?

**Comment by guzba** [comment]
Hi and happy to hear the project has caught your interest. I think there is a lot we can do to improve Mummy. Here is my personal perspective right now.

The most important thing I think that Mummy will benefit from is actual projects using it. Even just tiny demos that run locally. But ideally it would be things that people can visit from their browser and see the source code of (that I can link to here as well).

A concrete example of this is I am pretty much done with a rewrite that migrates NimDocs.com to use Mummy (branch link): https://github.com/treeform/nimdocs/tree/ryan. This'll be an open source website that shows how Mummy can be used by a real website on the internet.

I'll happily link to examples and provide feedback on how to get the most out of Mummy for those experimenting with it.

Additionally, actually using Mummy to build something will help identify shortcomings that can be addressed. I like this idea of "run into a shortcoming" more than "think up cool ideas to add" because it is so much more real and easy to discuss when there are concrete examples of the need.

I realize this isn't a list of "what to do" but I think if you're interested in Mummy, maybe try using it to get some little project working locally and perhaps grow from that into something fun on the internet. Little things like "a website that takes a number and hex encodes it" or "upload an image and get it turned black-and-white" or a personal homepage or the like. Tons of little things that will run face first into real issues we can work to improve.

**Comment by jasonprogrammer** [comment]
Thanks! I think I'll try and build some things on top of this. Ultimately what I'm hoping to do is build a web framework (to do things like routes with pattern matching/variables, serve static files from a directory, read query params, etc.)
