### ISSUE TITLE
mummy only serves on ipv6 since 0.3.0 without specifying address.

### ISSUE THREAD

**Issue by ITwrx** [guzba/mummy#75]
since i updated to `0.3.0` i get `502 bad gateway` if i use 

```
let server = newServer(router)
server.serve(Port(8080))
```

checking in the terminal with `ss -l -t -p` shows mummy listening on `[::]:*` only.

If i change my serve proc to `server.serve(Port(8080), address = "127.0.0.1")`  `ss` shows mummy listening on  `0.0.0.0:*` and it works in the browser again. It's also not listening on the ipv6 address anymore.

I'm running fedora 37 with ipv6 disabled in NetworkManager, btw.

thanks

**Comment by guzba** [comment]
Hm, well that is a bad default behavior. IPv6 support was contributed in https://github.com/guzba/mummy/pull/48 and tbh maybe I should remove it? Do people actually use IPv6? I will never need it (always behind reverse proxy lb) so I have not learned much about it.

**Comment by finitemonkey** [comment]
Hi! Yes, I tried to use it in an IPv6-only environment, and found that it didn't work, hence the patch.

Perhaps IPv4 should be assumed when no address is specified, even if IPv6 is available?  Maybe better, it should listen on IPv6 and IPv4 if both are available and neither is explicitly specified?  I think the first option ought to be very easy to do, but the second might be harder as I think Mummy makes the core assumption that it is only ever going to listening on one interface with one configuration.

Another option (as @guzba suggests) would be to drop IPv6 support.  It is a tiny change that would be easy to maintain out-of-tree if I wanted it.  It seems sort of defeatist though - the future is coming whether we like it or not!  Ok, fine, maybe it's coming very, very, very slowly in the case of IPv6... :-)

**Comment by finitemonkey** [comment]
Just to address the question about the websockets test - I think probably not important - it was just that the test was testing only IPv4, which obviously fails if you're listening on IPv6, so I changed the test to not make that assumption.  The only reason for the comment on it was that I think I had initially neglected to include it in the patch.

**Comment by ITwrx** [comment]
> Perhaps IPv4 should be assumed when no address is specified, even if IPv6 is available?

I think this is a reasonable default. It could always be revisited later. It might even be safer, in case the user is not aware ipv6 is enabled, and/or that mummy is listening on that address.

**Comment by finitemonkey** [comment]
PR #76 is ready for testing!

**Comment by guzba** [comment]
My issue with IPv6 is that I personally have no idea what I'm supporting. I am kind of shocked that localhost would default to IPv6. Is this always the case? When does that happen?

I know its "bad", but I have zero interest in becoming an IPv6 expert given all the other work I want to do, so now that I've seen IPv6 support has implications on default behavior I'm feeling very uneasy about promising to support it for others when I'll never use it myself.

Is it possible to craft a PR such that IPv6 will only be used when a user is explicitly asking for it? I would never ever want anyone to get IPv6 accidentally.

**Comment by finitemonkey** [comment]
I'm not sure if it is always the case, but I think for some years now IPv6 has been ready to go and actively used in most OSes, it's just that if your ISP only supports IPv4 (and most do only support that), you may never see it in action, except with localhost maybe.

I don't think you'll need to become an IPv6 expert because a web server only really needs to _lightly graze_ that layer to open a socket, but after that isn't it all HTTP?  One of the reasons the original PR was so easy was that it really doesn't affect anything other than the style of IP address when opening the socket.

I've update #76, so that the only way to get an IPv6 socket would be to explicitly specify an IPv6 style IP address, in the case of either not specifying any IP address or specifying "localhost", IPv4 will be forced.

For what it's worth, I think this is the wrong approach.  I think that the web server should work with the environment it is in, wherever possible.  I.e. If the OS would open an IPv6 socket given the parameters provided, that is what the user would expect and that is what the user should get.  The web server probably shouldn't attempt to subvert that.

**Comment by finitemonkey** [comment]
Actually, I think "what the user would expect" in most cases is going to be whatever Apache, NGINX, et al. would do.

And they would, I think, if "localhost" resolved to an IPv4 and an IPv6 address, open sockets for both.

I don't think mummy is able to do that at present, though?

**Comment by guzba** [comment]
I am not at PC now so I need to sit down and read the full post but I do agree with this statement:

> Actually, I think "what the user would expect" in most cases is going to be whatever Apache, NGINX, et al. would do.

I will be back on this later but that strikes me as eminently reasonable.

**Comment by guzba** [comment]
Let me rewind the tape and start from the top. This issue was opened because Mummy was only listening on IPv6 localhost even though IPv6 was disabled in NetworkManager. How this situation arise?

It appears Mummy would use `Domain.AF_UNSPEC` and then create a socket based on what the `getAddrInfo` syscall returned. Something seems wrong about this outcome. Before I jump to any further conclusions I'd like to start by understanding this.

**Comment by guzba** [comment]
Potentially related: https://stackoverflow.com/questions/55627377/getaddrinfo-returns-only-ipv6-when-using-af-unspec

**Comment by finitemonkey** [comment]
I've just re-read the OP and there's a potential issue.  This could be just a couple of typos, but experience tells me to always check anyway!

@ITwrx says that mummy is listening on [::], but if no address is given to serve(), it will use "localhost" (which should be [::1] in IPv6 land).  Again, when the OP says that they specified 127.0.0.1, mummy was listening on 0.0.0.0, which I don't think it should be either (and if it is, isn't that another bug and security problem?).

**Comment by ITwrx** [comment]
i just checked again with `server.serve(Port(8080))` and now `ss -l -t ` (less verbose output than `ss -l -t -p` )  shows: 

`0.0.0.0:http` and `[::]:http` for the `Local Address: Port`, but i still get `502` error. Maybe the ipv4 hid from me last time, but i kind of doubt it, though i have no idea what would cause a variation.  

with `server.serve(Port(8080), address = "127.0.0.1")` i get:

`0.0.0.0:http` and `[::]:http` but no 502. serves fine. using nginx  as reverse proxy via `proxy_pass http://127.0.0.1:8080/` with `127.0.0.1` for local domain in `/etc/hosts` for nginx `server_name` and static files. 

yeah, i think i forgot to mention, or missed, the `0.0.0.0` issue. I'm behind a firewall right now, but not so great for production.  

ipv6 is still disabled in NetworkManager and still on mummy 0.3.0. Someone might want to reproduce in case there's something specific to my env.

**Comment by finitemonkey** [comment]
I'm wondering whether there is a web server already running on your machine?  I'm just wondering why are you seeing something listening on all-interfaces when you specify a specific interface?  What output do you get when Mummy is not running?

**Comment by ITwrx** [comment]
Thanks!
!@$% i didn't see the `-n` option for `ss`... i knew i didn't like it showing the service names only, but i didn't look well enough for alt options...so `ss` was showing `nginx` on `port 80` as `http` too, of course.

so, with `nginx` stopped...

with `server.serve(Port(8080))` i get:

`[::1]:8080` 

what's really strange is if i visit `http://localhost:8080`, mummy serves the app somehow! If i had nginx running it would 502... For the record `ip a` doesn't show an ipv6 address for my ethernet interface either, so it's not just NetworkManager lying. :) IDK/remember, maybe ipv6 localhost still works even though ipv6 is disabled otherwise, by design?

with `server.serve(Port(8080), address = "127.0.0.1")`  i get:

`127.0.0.1:8080` only. `mummy` still serves the app on `http://localhost:8080`

**Comment by ITwrx** [comment]
i was looking at the lan interface and not the loopback with `ip a` when wondering about localhost! 
lol, how embarrassing. :) 

lo is:

`inet6 ::1/128 scope host`

so that explains why that works. I guess it's just a question of defaults at this point.

**Comment by finitemonkey** [comment]
Don't worry - I only knew to ask because I've done the literal exact same thing! :-)

You might be right about Network Manager, although I don't use it myself and the last time I saw it in action was I think over 10 years ago!  It used to be focused on allowing the end user to easily connect to transient networks like WiFi hotspots, and so perhaps the loopback and maybe other interfaces are dealt with elsewhere (certainly that used to be the case back then if I remember correctly).

The behaviour of Mummy that you're describing there sounds correct and as designed at the moment.  It can only listen on one socket at the moment.  I'm not sure if this would align with @guzba's plans for Mummy as a back-end/proxy server, but it might be useful to make it listen on multiple addresses and ports if it was to evolve into a more general purpose web server, if only to deal with IPv4 + IPv6 and/or http + https in one instance.

@guzba What do you think about defaults?  Should PR #76 be discarded or changed?  My vote would be to drop it, as I don't think it will fix anything but it does add a restriction that might cause future issues.

**Comment by guzba** [comment]
@finitemonkey I think dropping #76 is best. Assuming it is currently behaving in a sensible way, which appears to be the case, I don't think messing around with things is necessary.

Listening on multiple addresses / ports is something I have had working in a branch at one point, I don't recall it being a big deal and it could be revisited at some point.

**Comment by ITwrx** [comment]
@guzba  maybe you lost track due to all my mistakes and posts, but it's still doing what i said in the original post, except it's serving over `127.0.0.1` like it's supposed to _when the ip is specified_, instead of `0.0.0.0`, as i incorrectly reported.

I don't have a strong opinion on how you decide to handle it, but if it's going to serve over ipv6 by default when no address is specified (the way it's documented to be used), even when ipv6 is disabled in NetworkManager, you might want to update the docs to specify an address, as the default results in a 502 when using with a reverse proxy config (that expects ipv4), and is served over ipv6 lo regardless of reverse proxy, neither of which would be expected. I had to search for the syntax for specifying the address, for instance.

I don't use NetworkManager for non-desktop machines either, but it is probably the most common for Ganoo/Linox desktop OSes, so i doubt i'm an outlier in this regard.

**Comment by guzba** [comment]
I am genuinely sorry finitemonkey, I really appreciate your patience and helpfulness and I wish this could have worked out better, but I really have no interest in figuring out what is going on here or why, for the sake of IPv6.

I do not understand all the Linux settings and defaults affecting this. I do not know what the defaults for other flavors of Linux are. I do not want to take the time to learn when I have so many other more fun things to work on.

I am going to revert IPv6 support and just do simple IPv4 which I can understand, actively use, and will be able to maintain for the foreseeable future.

**Comment by guzba** [comment]
Reverted and tagged in https://github.com/guzba/mummy/releases/tag/0.3.1

**Comment by finitemonkey** [comment]
Thanks @guzba, I understand, and appreciate the consideration toward me about it but it is a totally logical decision to make.

I might have a go at reintroducing the multiple socket listening code in my own fork, and see how that goes!
